version: '2'
services:
  ui:
    build: ./ui
    ports:
      - '82:80'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8082:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
